# Generated by Django 5.1.4 on 2025-04-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('qualification', models.CharField(blank=True, default='Not Mentioned', max_length=50, null=True)),
                ('prof_qualification', models.CharField(blank=True, default='Not Mentioned', max_length=50, null=True)),
                ('personalno', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(choices=[('SST Arts', 'SST Arts'), ('SST', 'SST'), ('SSE Arts', 'SSE Arts'), ('SSE English', 'SSE English'), ('SSE Science', 'SSE Science'), ('SST MATH', 'SST MATH'), ('SST science', 'SST science'), ('SST BIO', 'SST BIOLOGY'), ('SST PHY', 'SST PHYSICS'), ('SST CHE', 'SST CHEMISTRY'), ('SST IT', 'SST COMPUTER'), ('EST Arts', 'EST Arts'), ('EST Sci', 'EST Science'), ('EST Arts', 'EST Arts'), ('EST', 'EST'), ('SESE', 'SESE'), ('EST Agri', 'EST Agri'), ('EST General', 'EST General'), ('EST Vr', 'EST Vernacular'), ('PST Sci', 'PST Science'), ('PST Arts', 'PST Arts'), ('PST', 'PST'), ('Naib Qasid', 'Naib Qasid'), ('L.Attendant', 'Lab Attendant'), ('Mali', 'Mali'), ('C.IV', 'Class 4'), ('SG', 'Security Guard'), ('Chokidat', 'Chokidar'), ('Sweaper', 'Sweaper')], max_length=20)),
                ('scale', models.CharField(choices=[('19', '19'), ('18', '18'), ('17', '17'), ('16', '16'), ('15', '15'), ('14', '14'), ('12', '12'), ('9', '9'), ('7', '7'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=3)),
                ('post_status', models.CharField(choices=[('Regular', 'Regular'), ('Contract', 'Contract'), ('temporary', 'temporary'), ('Other', 'Other')], default='Regular', max_length=15)),
                ('date_of_birth', models.DateField()),
                ('date_of_first_joining', models.DateField(blank=True, null=True)),
                ('date_of_joining_present_scale', models.DateField(blank=True, null=True)),
                ('date_of_joining_present_school', models.DateField(blank=True, null=True)),
                ('date_of_regularization', models.DateField(blank=True, null=True)),
                ('accountno', models.CharField(max_length=50, unique=True)),
                ('bank', models.CharField(max_length=100)),
                ('phoneno', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, default='not_mentioned@g.com', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='defaults/noimage.jpg', upload_to='school/images')),
            ],
        ),
    ]
