# Generated by Django 5.1.4 on 2025-04-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle_name', models.CharField(max_length=255)),
                ('principle_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('deputed', 'Deputed'), ('other', 'Other')], max_length=20)),
                ('total_rooms', models.PositiveIntegerField()),
                ('wash_rooms', models.PositiveIntegerField()),
                ('classes', models.PositiveIntegerField()),
                ('sections', models.PositiveIntegerField()),
                ('enrollment', models.PositiveIntegerField()),
                ('teachers', models.PositiveIntegerField()),
                ('non_teaching_staff', models.PositiveIntegerField()),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('covered_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('furniture_students', models.TextField(blank=True, null=True)),
                ('furniture_teachers', models.TextField(blank=True, null=True)),
                ('science_lab', models.BooleanField(default=False)),
                ('computer_lab', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='school_logos/')),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('category', models.CharField(choices=[('main', 'Main Banner Slider'), ('middle', 'Achievements Slider'), ('bottom', 'News & Ads Slider')], max_length=10)),
            ],
        ),
    ]
